# default_model_path: "models/yolov8n.pt"
# dataset_directory: "dataset/coco128.v1i.yolov8"
# initial_iou_threshold: 0.5
# confidence_threshold: 0.2
# image_size: 1280
# percentage: 100
# use_half_precision: true
# num_processes: 8
# dataset_splits:
#   - train
#   - valid
#   - test


default_model_path: "C:/Users/James/Downloads/MS-v8n-4096-0517.pt"
dataset_directory: "C:/Users/James/Downloads/MasterSplitv2.v5i.yolov8"
initial_iou_threshold: 0.5
confidence_threshold: 0.2
image_size: 4096
percentage: 5
use_half_precision: true
num_processes: 8
dataset_splits:
  - train
  - valid
  - test
